#!/bin/sh
#
# Copyright 2017, Population Health Research Institute
# Copyright 2017, Martin Renters
#
# This file is part of the DataFax Toolkit.
#
# The DataFax Toolkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The DataFax Toolkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with The DataFax Toolkit.  If not, see <http://www.gnu.org/licenses/>.
#

##########################################################################
# Generate an annotated CRF PDF file
#
# Initial: Martin Renters, 2017-02-13
##########################################################################
if [ $# -lt 1 ]
then
	echo "No study Specified"
	exit 2;
fi

STUDY_DIR=`$DATAFAX_DIR/bin/DFgetparam.rpc -s $1 STUDY_DIR`
if [ -z "$STUDY_DIR" ]
then
	echo "Unable to determine STUDY_DIR"
	exit 2
fi
shift

/opt/datafax/PHRI/python27 $DATAFAX_DIR/PHRI/annotate.py --studydir $STUDY_DIR "$@"
